repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Gitleaks staged scan
        entry: gitleaks protect --staged --no-banner --redact 1>&2
        language: system
        stages: [pre-commit, pre-push]
